### ISSUE TITLE
Units of location

### ISSUE THREAD

**Issue by adam2392** [Upward-Spiral-Science/the-vat#1]
We were wondering what the units of location was in the syanpsinR_7thA_tif.Pivots.txt file?

**Comment by jovo** [comment]
great question!
i don't know, post the min & max and some other summary statistics, and let's figure it out!

**Comment by adam2392** [comment]
According to this http://www.nature.com/articles/sdata201446/tables/3

the units are in pixels with resolution being at nm/pixel in each x,y,z direction.
