### ISSUE TITLE
Questions about the features

### ISSUE THREAD

**Issue by tyler-tomita** [Upward-Spiral-Science/the-vat#2]
- What are the identities of the features or is it better to not know them in order to not bias the results?
- Are any of them categorical?
- Is it possible that there are missing values? We could check but if you know off the top of your head it that would be nice :)

**Comment by jovo** [comment]
1) https://github.com/Upward-Spiral-Science/data/blob/master/syn-diversity/features.md
2) check and tell me!
3) check and tell me!

**Comment by tyler-tomita** [comment]
Regarding the https://github.com/Upward-Spiral-Science/data/blob/master/syn-diversity/features.md file - Do these just refer to the first 6 features of the 144? Are these manually constructed features from the raw image data?

**Comment by jovo** [comment]
144/6 = ??

i just updated the readme

**Comment by adam2392** [comment]
@jovo "...f4,f5 are features that I forget what they are.. would need to ask brad. i would throw them out, I did so in my kohonen code (which you have, its in matlab)."

Where can we find this code?

**Comment by jovo** [comment]
the readme file in the relevant folder in the 'data' repo

On Fri, Feb 12, 2016 at 12:21 AM, Adam Li notifications@github.com wrote:

> @jovo https://github.com/jovo "...f4,f5 are features that I forget what
> they are.. would need to ask brad. i would throw them out, I did so in my
> kohonen code (which you have, its in matlab)."
> 
> Where can we find this code?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Upward-Spiral-Science/the-vat/issues/2#issuecomment-183184361
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by adam2392** [comment]
Synapse Data:
- Excitatory presynaptic: ‘Synap’, ‘Synap’, ‘VGlut1’, ‘VGlut1’, ‘VGlut2’,
- Excitatory postsynaptic: ‘psd’, ‘glur2’, ‘nmdar1’, ’nr2b’, ’NOS’, ’Synapo’ (but further away than PSD, gluR2, nmdar1 and nr2b) ...

I was wondering 2 things:
1) When you wrote this in the READMe, is this representative of the 24 columns within each metric of the feature matrix? (e.g. the first 24 cols represent f0, which is integrated brightness and then the 24 columns correspond to the integrated brightness of these proteins?)
2) What is the order of the proteins being expressed in the feature matrix? You list some excitatory/inhibitory and presyn and postsyn, but not sure on their order within the actual dataset and what columns correspond to which proteins.

**Comment by jovo** [comment]
updated readme.

On Sun, Feb 14, 2016 at 12:19 AM, Adam Li notifications@github.com wrote:

> Synapse Data:
> - Excitatory presynaptic: ‘Synap’, ‘Synap’, ‘VGlut1’, ‘VGlut1’,
>   ‘VGlut2’,
> - Excitatory postsynaptic: ‘psd’, ‘glur2’, ‘nmdar1’, ’nr2b’, ’NOS’,
>   ’Synapo’ (but further away than PSD, gluR2, nmdar1 and nr2b) ...
> 
> I was wondering 2 things:
> 1) When you wrote this in the READMe, is this representative of the 24
> columns within each metric of the feature matrix? (e.g. the first 24 cols
> represent f0, which is integrated brightness and then the 24 columns
> correspond to the integrated brightness of these proteins?)
> 2) What is the order of the proteins being expressed in the feature
> matrix? You list some excitatory/inhibitory and presyn and postsyn, but not
> sure on their order within the actual dataset and what columns correspond
> to which proteins.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Upward-Spiral-Science/the-vat/issues/2#issuecomment-183822978
> .

## 

the glass is all full:  half water, half air.
neurodata.io
