### ISSUE TITLE
Best Suggestions For "Missing Data"

### ISSUE THREAD

**Issue by adam2392** [Upward-Spiral-Science/the-vat#5]
Just wondering out of curiosity what the best practices/algorithms were for dealing with missing entries in our data (if our data had missing entries)? 
- ignore?
- try to predict them?

**Comment by jovo** [comment]
what's the _simplest_ thing to do?

On Sat, Feb 20, 2016 at 2:57 PM, Adam Li notifications@github.com wrote:

> Assigned #5 https://github.com/Upward-Spiral-Science/the-vat/issues/5
> to @jovo https://github.com/jovo.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Upward-Spiral-Science/the-vat/issues/5#event-557778874
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by adam2392** [comment]
I would guess to just ignore those rows, but if you have many rows affected, what would be techniques that I can research to help fill these in?

**Comment by jovo** [comment]
my advise: always start by ignoring and see what you get.
if for some reason, you believe downstream inferential results will
strongly depend on those missing values, then you can impute.
in R, the impute package is kind of a standard,
but the real answer depends on the nature of the data.

how that helps?

On Sun, Feb 21, 2016 at 9:59 PM, Adam Li notifications@github.com wrote:

> I would guess to just ignore those rows, but if you have many rows
> affected, what would be techniques that I can research to help fill these
> in?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Upward-Spiral-Science/the-vat/issues/5#issuecomment-186978602
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by adam2392** [comment]
That helps! This was more for a side Kaggle project I'm exploring and I figured imputation could also be helpful here if we had missing/noisy data.
